// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { HostsId } from "./Hosts";

/** Identifier type for public.accommodations */
export type AccommodationsId = string & { __brand: "public.accommodations" };

/** Represents the table public.accommodations */
export default interface Accommodations {
  id: AccommodationsId;

  title: string;

  description: string | null;

  neighborhood_overview: string | null;

  images: string;

  host_id: HostsId;

  lattitude: string;

  longitude: string;

  property_type: string;

  room_type: string;

  accommodates: number;

  bathrooms: string;

  bathrooms_text: string;

  bedrooms: number;

  beds: number;

  price: number;

  has_availability: boolean;

  created_at: Date | null;

  updated_at: Date | null;

  amenities: string[] | null;

  country: string;

  location: string;

  rating: number | null;
}

/** Represents the initializer for the table public.accommodations */
export interface AccommodationsInitializer {
  id: AccommodationsId;

  title: string;

  description?: string | null;

  neighborhood_overview?: string | null;

  images: string;

  host_id: HostsId;

  lattitude: string;

  longitude: string;

  property_type: string;

  room_type: string;

  accommodates: number;

  bathrooms: string;

  bathrooms_text: string;

  bedrooms: number;

  beds: number;

  price: number;

  has_availability: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  amenities?: string[] | null;

  country: string;

  location: string;

  rating?: number | null;
}

/** Represents the mutator for the table public.accommodations */
export interface AccommodationsMutator {
  id?: AccommodationsId;

  title?: string;

  description?: string | null;

  neighborhood_overview?: string | null;

  images?: string;

  host_id?: HostsId;

  lattitude?: string;

  longitude?: string;

  property_type?: string;

  room_type?: string;

  accommodates?: number;

  bathrooms?: string;

  bathrooms_text?: string;

  bedrooms?: number;

  beds?: number;

  price?: number;

  has_availability?: boolean;

  created_at?: Date | null;

  updated_at?: Date | null;

  amenities?: string[] | null;

  country?: string;

  location?: string;

  rating?: number | null;
}
