// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BookingsId } from './Bookings';

/** Identifier type for public.addresses */
export type AddressesId = number & { __brand: 'public.addresses' };

/** Represents the table public.addresses */
export default interface Addresses {
  id: AddressesId;

  booking_id: BookingsId;

  street_address: string;

  city: string;

  state: string;

  zip: string;

  country: string;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.addresses */
export interface AddressesInitializer {
  id: AddressesId;

  booking_id: BookingsId;

  street_address: string;

  city: string;

  state: string;

  zip: string;

  country: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.addresses */
export interface AddressesMutator {
  id?: AddressesId;

  booking_id?: BookingsId;

  street_address?: string;

  city?: string;

  state?: string;

  zip?: string;

  country?: string;

  created_at?: Date | null;

  updated_at?: Date | null;
}
