// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccommodationsId } from './Accommodations';
import type { HostsId } from './Hosts';

/** Identifier type for public.bookings */
export type BookingsId = number & { __brand: 'public.bookings' };

/** Represents the table public.bookings */
export default interface Bookings {
  id: BookingsId;

  accommodation_id: AccommodationsId;

  host_id: HostsId;

  name: string;

  email: string;

  phone: string;

  guests: number;

  nights: number;

  check_in_date: Date;

  check_out_date: Date;

  created_at: Date | null;

  updated_at: Date | null;

  total_price: string;
}

/** Represents the initializer for the table public.bookings */
export interface BookingsInitializer {
  id: BookingsId;

  accommodation_id: AccommodationsId;

  host_id: HostsId;

  name: string;

  email: string;

  phone: string;

  guests: number;

  nights: number;

  check_in_date: Date;

  check_out_date: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  total_price: string;
}

/** Represents the mutator for the table public.bookings */
export interface BookingsMutator {
  id?: BookingsId;

  accommodation_id?: AccommodationsId;

  host_id?: HostsId;

  name?: string;

  email?: string;

  phone?: string;

  guests?: number;

  nights?: number;

  check_in_date?: Date;

  check_out_date?: Date;

  created_at?: Date | null;

  updated_at?: Date | null;

  total_price?: string;
}
