// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.hosts */
export type HostsId = number & { __brand: 'public.hosts' };

/** Represents the table public.hosts */
export default interface Hosts {
  id: HostsId;

  name: string;

  location: string;

  about: string | null;

  thumbnail_url: string | null;

  picture_url: string | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.hosts */
export interface HostsInitializer {
  id: HostsId;

  name: string;

  location: string;

  about?: string | null;

  thumbnail_url?: string | null;

  picture_url?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.hosts */
export interface HostsMutator {
  id?: HostsId;

  name?: string;

  location?: string;

  about?: string | null;

  thumbnail_url?: string | null;

  picture_url?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
