// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BookingsId } from './Bookings';

/** Identifier type for public.payments */
export type PaymentsId = number & { __brand: 'public.payments' };

/** Represents the table public.payments */
export default interface Payments {
  id: PaymentsId;

  booking_id: BookingsId;

  card_number: string;

  cardholder_name: string;

  expiration_date: string;

  cvv: string;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.payments */
export interface PaymentsInitializer {
  id: PaymentsId;

  booking_id: BookingsId;

  card_number: string;

  cardholder_name: string;

  expiration_date: string;

  cvv: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.payments */
export interface PaymentsMutator {
  id?: PaymentsId;

  booking_id?: BookingsId;

  card_number?: string;

  cardholder_name?: string;

  expiration_date?: string;

  cvv?: string;

  created_at?: Date | null;

  updated_at?: Date | null;
}
